### ISSUE TITLE
Maintainance level?

### ISSUE THREAD

**Issue by kelson42** [orblivion/KiwixSandstorm#3]
Is this repo maintained? Does it work with later versions of kiwix-serve?

**Comment by orblivion** [comment]
I haven't touched it in a while. I would like to update it at some point within the next month or two though.

I plan to use a newer version of Debian than what I used here, which I hope means I have to build a lot fewer dependencies, and maintenance would be a lot easier going forward. (Ideally some day Kiwix itself will be in Debian).

**Comment by kelson42** [comment]
I would really recommend to use the newest version of kiwix-serve... and also: why not using the binary package of kiwix-serve we distribute? This would really simplify a lot the package?

**Comment by orblivion** [comment]
I agree that we should update kiwix-serve. Sandstorm development has a sort of mental overhead I have to remind myself of before I get back into it. But I have a lot more free time as of this week so I do hope to get us on the latest kiwix-serve soon. I should note that we won't be able to use the content downloading feature you mentioned to me recently, because I'd have to learn how to poke holes from Sandstorm to the outside world (part of Sandstorm's security model).

As for binaries - I agree it would have massively simplified the creation of the package in the past. However, my understanding is that Sandstorm at least ideally tries to follow the same spirit as Linux distributions of building packages from source instead of just taking binary from the upstream authors, with the exception that we can use packages from other major repos since Sandstorm itself is not a whole operating system from scratch. I'm doing my best to follow that spirit, for whatever it's worth.

By the way, I appreciate your continued interest in my package here, and your poking me to keep it up to date. I didn't realize this was still on your radar.

**Comment by ocdtrekkie** [comment]
I think the biggest concern with "just using binaries" is that everyone wants to know where they came from. If your script is pulling open source software straight from the original developers' server, it is probably a pretty healthy strategy.

vagrant-spk-built packages are scripting where everything is coming from, so that's a pretty feasible option. For an spk-built package, you're just putting the files you built the package with in your repo, and it's probably not ideal to upload binaries in that case, because you can't see either where you got them or what's in them.

**Comment by orblivion** [comment]
When I described my desire to do it the way I did to Asheesh back in the day, I got the impression from him that building from source + high profile repos is at least a "nice to have". I'm curious what Kenton would say. If he sees no value in building from source, then sure, I may as well just use binaries. (I'd still have some bigger-picture questions about that, but I won't bring that discussion into this thread).

**Comment by ocdtrekkie** [comment]
@orblivion I'm just expressing my opinion, personally. I think the binaries in an open source package must be able to be sourced. But I am not sure that requires you must build from source yourself. And there's nothing wrong with doing it the way you desire to either. ;)

**Comment by orblivion** [comment]
Got it. I have some thoughts in response and I'm curious about your opinion on those, and also Kenton's thoughts. But I'll continue on the sandstorm dev list.

**Comment by kelson42** [comment]
@orblivion Let me know if you want anything from us. A lot of work has been not these last two years and I have a bit more resources now to focus on people doing ports. If you are seriously interested to continue your work on the Sandstorm port, we would probably both benefits to embeds you a bit more in our processes/team so you get better information/support about what we are doing and the other way around, we could also better advert your work.

**Comment by orblivion** [comment]
Thanks. The gang at Sandstorm-dev is on their way to convincing me to just use your binaries if I have any trouble building from source. I just need to get around to it, which will hopefully be soon.

As for investing your time into this - I do appreciate it. I would say that I'd be curious to gauge the level of interest in Kiwix-Sandstorm. I came into this project thinking it would be a neat use case for Sandstorm that nobody thought of, and/or an easier way to set up and maintain Kiwix as a server. However upon reflection, I wonder if I was misguided, for two reasons. Firstly, in my excitement over the concept of Sandstorm, I glossed over the fact that it's targeted as a personal productivity suite. There are some publishing capabilities, but they're secondary, and besides, the server as I understand isn't optimized for lots of viewers. Secondly, if Kiwix is on its way to the Debian repo anyway, and if OPDS means that you're adding library/downloading functionality to kiwix-server (and I'm not sure if this is the case or not), I wonder if the Sandstorm app is actually _more_ overhead for the user rather than less?

Sandstorm doesn't have a great way of counting users of an application, so I'm curious if anybody out there is actually enjoying it. I'd be curious about your opinion about its usefulness, since you were interested enough to ask me about this again.

All that said, I would like to keep up with basic updates for now. I'm just not sure how much of everyone's time (mine included) I should use.

**Comment by ocdtrekkie** [comment]
Very old/incomplete data (2017): https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/sandstorm-dev/_JpC1Xze6q0/VvJG5yNhAQAJ But there is some data out there that exists. That was only a couple months after you released the app, I believe.

I feel like Sandstorm's "targeting" was largely motivated by what the Sandstorm-the-business was hoping to achieve, rather than what Sandstorm-the-project potentially makes sense for. During the original campaign and setup, there was a lot more odd-and-end apps being built for it by the Sandstorm team, fun stuff like games and the like. I see it as a generic personal use app platform.

**Comment by orblivion** [comment]
I think "Personal use" is the key here. I tried to sell the idea of Kiwix-on-Sandstorm to a friend who's working on a mesh networking project. "Imagine if we had our own apps running locally. Sandstorm makes it easy, including this thing called Kiwix that lets you host a local copy of Wikipedia and..." And he thought Sandstorm and Kiwix were both cool, but figured it made more sense to install Kiwix separately.

Plus it has this weird hash URL thing, it makes it a little weird as a public URL. And so on.

**Comment by orblivion** [comment]
@kelson42 I just pushed a version that uses the binary release of kiwix-tools_linux-x86_64-3.0.1. Didn't bother with building from scratch anymore. Also used the new "hide library button" feature since I only have one file per instance for now.

@ocdtrekkie Also switched to spk, in case you wanted to look over my repo. Otherwise, the spk is in the release queue!

**Comment by orblivion** [comment]
("switched to spk" meaning, from vagrant-spk)

**Comment by kelson42** [comment]
> Secondly, if Kiwix is on its way to the Debian repo anyway, and if OPDS means that you're adding library/downloading functionality to kiwix-server (and I'm not sure if this is the case or not), I wonder if the Sandstorm app is actually _more_ overhead for the user rather than less?

The OPDS stream is a feature of `kiwix-serve` and is always available if you run it. Download feature is not done for the moment, but we go in that direction (see https://github.com/kiwix/kiwix-tools/issues/344)

**Comment by kelson42** [comment]
> @kelson42 I just pushed a version that uses the binary release of kiwix-tools_linux-x86_64-3.0.1. Didn't bother with building from scratch anymore. Also used the new "hide library button" feature since I only have one file per instance for now.

Nice but I don't see any update at https://apps.sandstorm.io/app/5uh349d0kky2zp5whrh2znahn27gwha876xze3864n0fu9e5220h... or the update date is still wrong?

**Comment by orblivion** [comment]
Oops I forgot to explain - I still need it to be approved by @ocdtrekkie before it's actually released. However you can see it now if you add `?experimental=true` to the URL.

**Comment by kelson42** [comment]
@orblivion Looks good to me. Do you know how long it will take to get it published?

**Comment by ocdtrekkie** [comment]
It takes mostly until I get time to verify it's not broken. 🙃 I will try to get it done in the next day or three.

**Comment by ocdtrekkie** [comment]
It's been updated. Apparently it was in the next day or six. Sorry!

I did get a 502 Bad Gateway attempting to upgrade one existing Kiwix grain I had... but I couldn't replicate it at all, even trying other upgraded Kiwix grains. It may have just been on Oasis thing, since I tested on there.

**Comment by orblivion** [comment]
I did see the 502 at some point during transition on my server as well I believe.

**Comment by orblivion** [comment]
No worries on the time, thanks for getting to it!
